level_map=[
' rmmmmmmmqrmmmmmmmmquuuuuuuu ',
' n       pn        puuuuuuuu ',
' n       pn        puuuuuuuu ',
' n       pn        puuuuuuuu ',
' n  wvvvvtn   hj   puuuuuuuu ',
' n  zmmmmqn   pn   puuuuuuuu ',
' n       pn   pn   zmmmmuuuu ',
' n       iy   pn      f uuuu ',
' n            pn        uuuu ',
' n            pn   wvvvvuuuu ',
' n            pn   puuuuuuuu ',
' skkkkkvvvkvevtskkktuuuuuuuu ',
' uuuuuuuuuuuuuuuuuuuuuuuuuuu ',
' uuuuuuuuuuuuuuuuuuuuuuuuuuu ',
]
tiles = {
    'o': './assets/black.png',
    'u': './assets/tile.png',
    'v': './assets/topTile.png',
    'w': './assets/topTileLeftCorner.png',
    'x': './assets/topTileRightCorner.png',
    'y': './assets/bottomTileRightCorner.png',
    'z': './assets/bottomTileLeftCorner.png',
    'q': './assets/topTileLilCornerBottomLeft.png',
    'r': './assets/topTileLilCornerBottomRight.png',
    's': './assets/topTileLilCornerTopRight.png',
    't': './assets/topTileLilCornerTopLeft.png',
    'p': './assets/leftTile.png',
    'n': './assets/tileRight.png',
    'm': './assets/bottomTile.png',
    'l': './assets/AcidTop.png',
    'k': './assets/AcidTopTile.png',
    'j': './assets/AcidCorner_rechts_oben.png',
    'i': './assets/AcidtopTileLeftBottomCorner.png',
    'h': './assets/AcidtopTileLeft.png',
    'g': './assets/AcidtopTileRightBottomCorner.png',
    'f': './assets/FinishLine.png',
    'e': './assets/jumpTile.png',
    'b': './assets/ArrowDown.png',
    'c': './assets/ArrowRight.png',
    'd': './assets/ArrowUp.png'

}
tilsize = 64